routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use QRCode;

Route::get('/','DashboardController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function(){

Route::get('/Dashboard','DashboardController@index')->name('dashboard');

Route::get('/User-Levels','Settings@UserLevel')->name('user.level');
//Route::get('/Vendors','Settings@Vendors')->name('vendors');
Route::resource('transactions', 'TransactionController');
Route::get('transaction/users','TransactionController@user_earning')->name('transactions.user_earnings');
//user routes
Route::resource('/user', 'UsersController');
Route::get('users/data','UsersController@data')->name('user.data');
Route::get('city/get/{id}', 'UsersController@getCity')->name('get.city');

//vendor routes
Route::resource('/vendors', 'VendorsController');
Route::get('vendor/data','VendorsController@data')->name('vendor.data');

//category routes
Route::get('category/add','CategoryController@add')->name('category.add');
Route::get('category/view','CategoryController@index')->name('category.index');
Route::post('category/store','CategoryController@store')->name('category.store');
Route::get('category/get_sub_category/{id}/{count}','CategoryController@get_sub_category')->name('category.getsubcategory');
Route::get('category/get_sub_subcategory/{id}/{count}','CategoryController@get_sub_subcategory')->name('category.getsubsubcategory');
Route::get('category/update_order','CategoryController@updateorder')->name('category.updateorder');

Route::resource('levels', 'LevelController');
Route::post('level/calculate_earnings','LevelController@calculate_earnings')->name('level.calculate_earnings');

// Route::get('qr-code', function () 
// {		
// 	$file=public_path('generated_qrcodes/1.png');
//   	$encrypted = Crypt::encryptString('Hello world.');
//   	echo $encrypted;
//   	$decrypted = Crypt::decryptString($encrypted);
//   	echo $decryp;
//   	exit;
//   	$image=QRCode::text($encrypted)->setsize(4)->setMargin(2)->setOutfile($file)->png();    
//   	return $image;
// });
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
  @include('admin.layouts.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
@include('admin.layouts.header')
@include('admin.layouts.sidebar')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        @yield('title')
        <small>@yield('sub_title')</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ url('/admin/home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">@yield('title')</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
       @yield('content')
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@include('admin.layouts.footer')

</div>
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
	<strong>Copyright &copy; {{ date('Y', time()) }}</strong>
</footer>

<!-- jQuery 3 -->
<script src="{{ asset('public/lte/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('public/lte/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('public/lte/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Morris.js charts -->
<script src="{{ asset('public/lte/bower_components/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('public/lte/bower_components/morris.js/morris.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('public/lte/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<!-- jvectormap -->
<script src="{{ asset('public/lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('public/lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('public/lte/bower_components/jquery-knob/dist/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('public/lte/bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('public/lte/bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('public/lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('public/lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('public/lte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('public/lte/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- public/lteLTE App -->
<script src="{{ asset('public/lte/dist/js/adminlte.min.js') }}"></script>
<!-- public/lteLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('public/lte/dist/js/pages/dashboard.js') }}"></script>
<!-- public/lteLTE for demo purposes -->
<script src="{{ asset('public/lte/dist/js/demo.js') }}"></script>
<!-- jQuery Form -->
<script src="{{asset('public/lte/plugins/jquery-form/jquery.form.js')}}"></script>
<!-- Sweet Alert -->
<script src="{{asset('public/lte/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('public/lte/plugins/iCheck/icheck.min.js')}}"></script>
<script src="{{asset('public/lte/plugins/nestable/jquery.nestable.js')}}"></script>
@stack('scripts')
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="_token" content="{{ csrf_token() }}">
  <title>@yield('main_title')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('public/lte/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('public/lte/bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ asset('public/lte/bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('public/lte/dist/css/AdminLTE.min.css') }}">
  <!-- public/lteLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('public/lte/dist/css/skins/_all-skins.min.css') }}">
  @stack('styles')
  <!-- Date Picker -->
  <link rel="stylesheet" href="{{ asset('public/lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('public/lte/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ asset('public/lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
  <link rel="stylesheet" href="{{asset('public/lte/plugins/sweetalert/sweetalert.css')}}">
  <link rel="stylesheet" href="{{asset('public/lte/plugins/iCheck/square/blue.css')}}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<link rel="stylesheet" href="{{asset('public/lte/plugins/nestable/nestable.css')}}" />

resources/views/admin/layouts/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ route('dashboard')}}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>MLM</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>MLM</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">Admin</span>
            </a>
		  </li>
		  @if(isset(Auth::user()->name))
		  <li class="dropdown user user-menu">
            <a href="{{ route('logout') }}" onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
              <i class="fa fa-power-off"></i>
              <span class="hidden-xs">Sign out</span>
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
		  </li>
		  @else
			<script>window.location = "{{ route('login')}}";</script>
		   @endif
        </ul>
      </div>
    </nav>
  </header>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ asset('public/lte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Admin</p>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview">
		  <li class=""><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li class="treeview">
        <a href=""><i class="fa fa-users"></i>Customers
          <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{route('user.index')}}" class=""><i class="fa fa-list"></i>List Customers</a></li>
          <li><a href="{{route('user.create')}}" class=""><i class="fa fa-plus"></i>Add</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="">
          <i class="fa fa-truck"></i>Vendors
          <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{route('vendors.index')}}" class=""><i class="fa fa-list"></i>List Vendors</a></li>
          <li><a href="{{route('vendors.create')}}" class=""><i class="fa fa-plus"></i>Add</a></li>
         <!--  <li class="treeview">
            <a href="">
              <i class="fa fa-tags"></i>Category
              <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="{{route('category.index')}}" class=""><i class="fa fa-list"></i>List Categories</a></li>
              <li><a href="{{route('category.add')}}" class=""><i class="fa fa-plus"></i>Add</a></li>
            </ul>
          </li> -->
        </ul>
      </li>
      <li class="treeview">
        <a href="">
          <i class="fa fa-list-alt "></i>Category
          <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
              <li><a href="{{route('category.index')}}" class=""><i class="fa fa-list"></i>List Categories</a></li>
              <li><a href="{{route('category.add')}}" class=""><i class="fa fa-plus"></i>Add</a></li>
        </ul>
      </li>
        <li class="treeview">
        <a href="">
          <i class="fa fa-sitemap"></i>Levels
          <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
              <li><a href="{{route('levels.index')}}" class=""><i class="fa fa-list"></i>List Levels</a></li>
              <li><a href="{{route('levels.create')}}" class=""><i class="fa fa-plus"></i>Add</a></li>
        </ul>
      </li>

      <li class="treeview">
        <a href=""><i class="fa fa-book"></i>Transactions
          <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="{{route('transactions.create')}}" class=""><i class="fa fa-plus"></i>Add</a></li>
          <li><a href="{{route('transactions.index')}}" class=""><i class="fa fa-circle-o"></i>All Transaction</a></li>
          <li><a href="{{route('transactions.user_earnings')}}" class=""><i class="fa fa-circle-o"></i>User Earnings</a></li>
        </ul>
      </li>

      <li class="treeview">
        <a href=""><i class="fa fa-share"></i>Settings</a>
        <ul class="treeview-menu">
          <li><a href="{{route('user.level')}}" class=""><i class="fa fa-circle-o"></i>User Levels</a></li>
          <li><a href="#" class=""><i class="fa fa-circle-o"></i>Vendors</a></li>
        </ul>
      </li>
      <li class=""><a href=""><i class="fa fa-circle-o"></i>Transaction Report</a></li>

        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>