routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use QRCode;

Route::get('/','DashboardController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function(){

Route::get('/Dashboard','DashboardController@index')->name('dashboard');

Route::get('/User-Levels','Settings@UserLevel')->name('user.level');
//Route::get('/Vendors','Settings@Vendors')->name('vendors');
Route::resource('transactions', 'TransactionController');
Route::get('transaction/users','TransactionController@user_earning')->name('transactions.user_earnings');
//user routes
Route::resource('/user', 'UsersController');
Route::get('users/data','UsersController@data')->name('user.data');
Route::get('city/get/{id}', 'UsersController@getCity')->name('get.city');

//vendor routes
Route::resource('/vendors', 'VendorsController');
Route::get('vendor/data','VendorsController@data')->name('vendor.data');

//category routes
Route::get('category/add','CategoryController@add')->name('category.add');
Route::get('category/view','CategoryController@index')->name('category.index');
Route::post('category/store','CategoryController@store')->name('category.store');
Route::get('category/get_sub_category/{id}/{count}','CategoryController@get_sub_category')->name('category.getsubcategory');
Route::get('category/get_sub_subcategory/{id}/{count}','CategoryController@get_sub_subcategory')->name('category.getsubsubcategory');
Route::get('category/update_order','CategoryController@updateorder')->name('category.updateorder');

Route::resource('levels', 'LevelController');
Route::post('level/calculate_earnings','LevelController@calculate_earnings')->name('level.calculate_earnings');

// Route::get('qr-code', function () 
// {		
// 	$file=public_path('generated_qrcodes/1.png');
//   	$encrypted = Crypt::encryptString('Hello world.');
//   	echo $encrypted;
//   	$decrypted = Crypt::decryptString($encrypted);
//   	echo $decryp;
//   	exit;
//   	$image=QRCode::text($encrypted)->setsize(4)->setMargin(2)->setOutfile($file)->png();    
//   	return $image;
// });
});

app/Levels.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Levels extends Model
{
    //
    protected $table="levels";
    protected $guarded=['id'];
    protected $fillable=['name','start_node','end_node','percentage'];
}

app/Http/Controllers/Controllers/LevelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\levels;
class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $level=Levels::get()->toArray();
        return view('admin.levels.index',compact('level'));
    }

    public function data()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('admin.levels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validatedData = $request->validate([
        'level_name' => 'required|max:255',
        'level_percentage' => 'required',
    ]);
        // 'start_node' => 'required',
        // 'end_node'   => 'required',
        // 'start_node'=>$input['start_node'],
        //  'end_node'=>$input['end_node'],
        $input=$request->all();
        $data=array(
                    'name'=>$input['level_name'],
                    'percentage'=>$input['level_percentage'],
                    );
        Levels::create($data);
        return redirect('levels/create')->with('level_success','Level created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function calculate_earnings(Request $request)
    {
         $validatedData = $request->validate([
        'node_value' => 'required|integer',   
             ]);
         $node_value=$request->node_value;

         $levels=Levels::orderby('id','asc')->get()->toArray();  

           for($i=0;$i<sizeof($levels);$i++)
           {
            $previous_level_earnings=0;
                //current level earning
                $p_n_earning=$node_value*1/100;
                if($i==0)
                {
                    $node=pow(1,1);
                }
                else if($i==1)
                {
                    $node=pow(5,1);
                }
                else
                {
                    $node=pow(5,$i);
                }
                $current_level_earning=$node*$p_n_earning;
                // echo $current_level_earning."</br>";
               
                //previous level earning
                if($i > 0)
                {
                    $k=0;
                    $previous_level_earnings=0;
                   
                    for($j=$i;$j>0;$j--)
                    {
                        $p_n_earning1=$node_value*$levels[$j]['percentage']/100;
                        if($k==0)
                        {
                            $node=pow(1,1);
                        }
                        else if($k==1)
                        {
                            $node=pow(5,1);
                        }
                        else
                        {
                            $node=pow(5,$k);
                        }
                        
                        $previous_level_earnings+=$node*$p_n_earning1;
                        $k++;
                    }
                }
             

                 $total_earning=$current_level_earning+$previous_level_earnings;
                 
                 $data=array('earnings'=>$total_earning);

                 Levels::where('id',$levels[$i]['id'])->update($data);

            }
              return redirect('levels')->with('earning_success','Noode settings updated successfully');
           
    }
}

app/Http/Controllers/LevelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\levels;
class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $level=Levels::get()->toArray();
        return view('admin.levels.index',compact('level'));
    }

    public function data()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('admin.levels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validatedData = $request->validate([
        'level_name' => 'required|max:255',
        'level_percentage' => 'required',
    ]);
        // 'start_node' => 'required',
        // 'end_node'   => 'required',
        // 'start_node'=>$input['start_node'],
        //  'end_node'=>$input['end_node'],
        $input=$request->all();
        $data=array(
                    'name'=>$input['level_name'],
                    'percentage'=>$input['level_percentage'],
                    );
        Levels::create($data);
        return redirect('levels/create')->with('level_success','Level created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function calculate_earnings(Request $request)
    {
         $validatedData = $request->validate([
        'node_value' => 'required|integer',   
             ]);
         $node_value=$request->node_value;

         $levels=Levels::orderby('id','asc')->get()->toArray();  

           for($i=0;$i<sizeof($levels);$i++)
           {
            $previous_level_earnings=0;
                //current level earning
                $p_n_earning=$node_value*1/100;
                if($i==0)
                {
                    $node=pow(1,1);
                }
                else if($i==1)
                {
                    $node=pow(5,1);
                }
                else
                {
                    $node=pow(5,$i);
                }
                $current_level_earning=$node*$p_n_earning;
                // echo $current_level_earning."</br>";
               
                //previous level earning
                if($i > 0)
                {
                    $k=0;
                    $previous_level_earnings=0;
                   
                    for($j=$i;$j>0;$j--)
                    {
                        $p_n_earning1=$node_value*$levels[$j]['percentage']/100;
                        if($k==0)
                        {
                            $node=pow(1,1);
                        }
                        else if($k==1)
                        {
                            $node=pow(5,1);
                        }
                        else
                        {
                            $node=pow(5,$k);
                        }
                        
                        $previous_level_earnings+=$node*$p_n_earning1;
                        $k++;
                    }
                }
             

                 $total_earning=$current_level_earning+$previous_level_earnings;
                 
                 $data=array('earnings'=>$total_earning);

                 Levels::where('id',$levels[$i]['id'])->update($data);

            }
              return redirect('levels')->with('earning_success','Noode settings updated successfully');
           
    }
}

resources/views/admin/levels/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Levels')
@section('sub_title', 'Create Levels')
@section('content')
<div class="row">
   @if(Session::has('level_success'))
     <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Success!</h4>
                {{Session::get('level_success')}}
      </div>
    @endif
  	<div class="col-md-12">
		<div class="box box-primary">
			{!! Form::open(['route' => ['levels.store']]) !!}
            <div class="box-body">
                {{ csrf_field() }}
            	<div class="row">
                    <div class="col-md-6">
                        <div class="form-group {{ $errors->has('level_name') ? 'has-error' : ''}}">
                    		<label>Level Name</label>
            		  		{!! Form::text('level_name', null, array('placeholder' => 'Level Name','class' => 'form-control','id'=>'level_name')) !!}
                            {!! $errors->first('level_name', '<p class="help-block">:message</p>') !!}
                           
                    	</div>

                    </div>
                </div>
             <!--    <div class="row">
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('start_node') ? 'has-error' : ''}}">
                    		<label>Start Node</label>
            		  		{!! Form::text('start_node', null, array('placeholder' => 'Start Node','class' => 'form-control','id'=>'start_node')) !!}
                            {!! $errors->first('start_node', '<p class="help-block">:message</p>') !!}
                    	</div>
                    </div>   
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('end_node') ? 'has-error' : ''}}">
                    		<label>End Node</label>
            		  		{!! Form::text('end_node', null, array('placeholder' => 'End Node','class' => 'form-control','id'=>'end_node')) !!}
                            {!! $errors->first('end_node', '<p class="help-block">:message</p>') !!}
                    	</div>
                    </div>	
                </div> -->
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group {{ $errors->has('level_percentage') ? 'has-error' : ''}}">
                           {!! Form::label('percetage', 'Percentage(%)') !!}
                            {!! Form::text('level_percentage', null, array('placeholder' => 'Level Percentage(%)','class' => 'form-control','id'=>'level_percentage')) !!}
                            {!! $errors->first('level_percentage', '<p class="help-block">:message</p>') !!}
                        </div>
                    </div>
                </div>

                <div class="col-md-6  text-center">
                  <button type="submit" class="btn bg-blue btn-flat ajax-submit">Save</button>
                  <a href="" class="btn bg-red btn-flat">Cancel</a>
                </div>
            </div>

			{!! Form::close() !!}

		</div>
	</div>	
</div>

@endsection
@push('scripts')
@endpush

resources/views/admin/levels/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Levels')
@section('sub_title', 'Levels Listing')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			{!! Form::open(['route' => ['level.calculate_earnings']]) !!}
			<div class="box-body">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                    		{!! Form::text('node','1 Node', array('placeholder' => '','class' => 'form-control','id'=>'','disabled')) !!} 
                    	</div>

                    </div>
                    <div class="col-md-2">
                  			{!! Form::text('node_value', 1000, array('placeholder' => 'Rupees','class' => 'form-control','id'=>'node_value','')) !!}
                            {!! $errors->first('node_value', '<p class="help-block">:message</p>') !!}
                	</div>

                	<div class="col-md-2">
                  			 <button type="submit" class="btn bg-blue btn-flat ajax-submit">Save</button>
                 			 <a href="" class="btn bg-red btn-flat">Cancel</a>
                	</div>
                </div>
            </div>
			{!! Form::close() !!}
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
                <div class="box-header">
                    <a href="{{ route('levels.create') }}" class="btn bg-purple btn-flat pull-right"><i class="fa fa-plus"></i> Create New</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-striped table-responsive" id="example">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Percentage</th>
                                <th>Earnings</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@if(!empty($level))
                        	<?php 
                        	$total_earnings=0;
                        	?>
                        		@foreach($level as $l)
                        	<tr>
                        		<td>{{ $l['name'] }}</td>
                        		<td>{{ $l['percentage'] }}</td>
                        		<td>{{ $l['earnings'] }}</td>
                        		<?php
                        		$total_earnings+=$l['earnings'];
                        		?>
                        		<td>
                        			<a href="{{route('levels.show', $l['id'])}}" class="btn btn-sm bg-blue btn-flat" title="View User"><i class="fa fa-eye"></i></a>
                        			<a href="{{route('levels.edit', $l['id'])}}" class="btn btn-sm bg-green btn-flat" title="Edit User"><i class="fa fa-pencil"></i></a>
                        			<a href="#" id="{{ $l['id'] }} " data-src="{{route('levels.destroy', $l['id'])}}" class="btn btn-sm bg-red btn-flat delete" title="Delete User"><i class="fa fa-trash"></i></a>
                        		</td>
                        	</tr>
                        		@endforeach
                        		<tr>
                        			<td colspan="2">Total Earning
                        			</td>
                        			<td colspan="2">
                        				{{$total_earnings}}
                        			</td>
                        		</tr>
                        	@endif
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
	</div>
</div>
@endsection
@push('scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

@endpush